language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install --quiet -r requirements.txt
  - pip install pytest>=3.6
  - pip install pytest-cov
# command to run tests
script:
  - pytest --cov=./ test/

after_success:
  - bash <(curl -s https://codecov.io/bash)
